### PR TITLE
Address signature test issues from issue 681

### LINKED ISSUE #681: [Bug]: SignatureTest issues
### Specification Version

SNAPSHOT (Locally built)

### Bug report

I'm running into a few issues with running the ee.jakarta.tck.data.standalone.signature.SignatureTests. 
1. The DataSignatureTestRunner is looking for a jakarta.data.sig file resource, but what is in the tck jar are jakarta.data.sig_17 and jakarta.data.sig_21
2. The version of the maven-sigtest-plugin is old and needs to be updated to the forked version in jakarta tools, jakarta.tck:sigtest-maven-plugin:2.2
3. After fixing those 2, there continue to be static mode validation errors due to missing superclass/superinterfaces, but these seem to be due to the match attempt not considering the type parameters. For example, the  jakarta.data.Direction enum fails with a missing java.lang.Enum type, but the sigtest tool knows the superclass to be  java.lang.Enum<jakarta.data.Direction>. It seems there is a missing option to ignore type parameters.

### Additional information

For 1. I got the test to run by appending the runtime java specification version to the signature file resource name:

```diff
Index: tck/src/main/java/ee/jakarta/tck/data/framework/signature/DataSignatureTestRunner.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/tck/src/main/java/ee/jakarta/tck/data/framework/signature/DataSignatureTestRunner.java b/tck/src/main/java/ee/jakarta/tck/data/framework/signature/DataSignatureTestRunner.java
--- a/tck/src/main/java/ee/jakarta/tck/data/framework/signature/DataSignatureTestRunner.java	(revision 04b068591aa27a088c6d05bc899270c6fc09e672)
+++ b/tck/src/main/java/ee/jakarta/tck/data/framework/signature/DataSignatureTestRunner.java	(date 1712722145036)
@@ -229,8 +229,11 @@
 
 //            mapFileAsProps = getSigTestDriver().loadMapFile(mapFile);
 
+            String javaVersion = System.getProperty("java.specification.version");
+            String sigRsrc = SIG_RESOURCE_PACKAGE.replace(".", "/") + "/" + SIG_FILE_NAME;
+            sigRsrc += "_" + javaVersion;
             InputStream inStreamSigFile = DataSignatureTestRunner.class.getClassLoader()
-                    .getResourceAsStream(SIG_RESOURCE_PACKAGE.replace(".", "/") + "/" + SIG_FILE_NAME);
+                    .getResourceAsStream(sigRsrc);
             File sigFile = writeStreamToSigFile(inStreamSigFile);
             log.info("signature File location is :" + sigFile.getCanonicalPath());
             signatureRepositoryDir = System.getProperty("java.io.tmpdir");
```

For 2., replace the org.netbeans.tools:sigtest-maven-plugin:1.6 with jakarta.tck:sigtest-maven-plugin:2.2

```diff
Index: tck/pom.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/tck/pom.xml b/tck/pom.xml
--- a/tck/pom.xml	(revision 04b068591aa27a088c6d05bc899270c6fc09e672)
+++ b/tck/pom.xml	(date 1712727796074)
@@ -128,7 +128,7 @@
     
     <!-- Test Dependencies -->
     <dependency>
-      <groupId>org.netbeans.tools</groupId>
+      <groupId>jakarta.tck</groupId>
       <artifactId>sigtest-maven-plugin</artifactId>
       <version>${sigtest.version}</version>
     </dependency>
@@ -289,7 +289,7 @@
           
           <!-- Run signature plugin to generate signature file -->
           <plugin>
-            <groupId>org.netbeans.tools</groupId>
+            <groupId>jakarta.tck</groupId>
             <artifactId>sigtest-maven-plugin</artifactId>
             <version>${sigtest.version}</version>
             <executions>
```

I'll create a PR once I figure out what the issue with 3. is.

### PR DESCRIPTION
**Pull request by starksm64**
fixes #681

### CODE REVIEW

File: tck/src/main/java/ee/jakarta/tck/data/framework/signature/DataSignatureTestRunner.java [hunk 1]
```diff
@@ -229,8 +229,11 @@ public void signatureTest() throws Fault {
 
 //            mapFileAsProps = getSigTestDriver().loadMapFile(mapFile);
 
+            String javaVersion = System.getProperty("java.specification.version");
+            String sigRsrc = SIG_RESOURCE_PACKAGE.replace(".", "/") + "/" + SIG_FILE_NAME;
+            sigRsrc += "_" + javaVersion;
```
Comment (KyleAure) [inline tck/src/main/java/ee/jakarta/tck/data/framework/signature/DataSignatureTestRunner.java:234]: So I think this will break the signature tests for core/web/full profile.
https://github.com/jakartaee/data/blob/352d6366a6b071d521c244fb75a34670ce3f2fba/tck/src/main/java/ee/jakarta/tck/data/framework/arquillian/extensions/TCKArchiveProcessor.java#L109

When we deploy the app to the container to run the signature test we rename the resource without `_17` and `_21`

**Review by KyleAure — CHANGES_REQUESTED** [review]
We also need to update the deployment to package the new signature test plugin. 
https://github.com/jakartaee/data/blob/352d6366a6b071d521c244fb75a34670ce3f2fba/tck/src/main/java/ee/jakarta/tck/data/framework/arquillian/extensions/TCKArchiveProcessor.java#L95

@starksm64 I can open a different PR to do this work, or if you are able to test core profile you can update this PR.  Let me know.

File: tck/src/main/java/ee/jakarta/tck/data/framework/signature/DataSignatureTestRunner.java (hunk 1 above)
Comment (starksm64) [reply tck/src/main/java/ee/jakarta/tck/data/framework/signature/DataSignatureTestRunner.java:235]: Ok, I added a fallback to the base SIG_FILE_NAME if the jvm specification version cannot be found.

**Comment by starksm64** [comment]
> We also need to update the deployment to package the new signature test plugin.
> 
> https://github.com/jakartaee/data/blob/352d6366a6b071d521c244fb75a34670ce3f2fba/tck/src/main/java/ee/jakarta/tck/data/framework/arquillian/extensions/TCKArchiveProcessor.java#L95
> 
> @starksm64 I can open a different PR to do this work, or if you are able to test core profile you can update this PR. Let me know.

I add that change in the last commit

**Review by KyleAure — APPROVED** [review]
Ran locally and everything is working now. Thanks @starksm64

**Comment by gavinking** [comment]
I think this broke the build, maybe because we still have stuff like `<sigtest.version>1.6</sigtest.version>` in some places.
