### PR TITLE
Fix QBN issue in CDI tests

### LINKED ISSUE #640: [TCK Challenge]: ExtensionTests#testDataProviderWithBuildCompatibleExtension conflicts with QBN
### Specification

spec/src/main/asciidoc/repository.asciidoc

### Assertion

A valid Query by Method Name exists but the TCK is expecting something different

### TCK Version

SNAPSHOT (Locally built)

### Implementation being tested

HIbernate

### Challenge Scenario

Claims that a test assertion conflicts with the specification.

### Full Description

The `ExtensionTests#testDataProviderWithBuildCompatibleExtension` test is expecting that it can call the injected ee.jakarta.tck.data.common.cdi.Directory#findFirstNameByIdInOrderByAgeDesc() method and obtain a list of `Person.firstName` values as though the repository was annotated with:

```java
@Repository(provider = Directory.PERSON_PROVIDER)
public interface Directory extends DataRepository<Person, Long> {
    @Query("select firstName from Person where id in ?1 order by age desc")
    List<String> findFirstNameByIdInOrderByAgeDesc(List<Long> ids);
}
```

while `findFirstNameByIdInOrderByAgeDesc` is a valid QBN method that parses to:
find-expression: findFirst
ignored-text: Name
predicate: id IN 
order-clause: OrderBy age Desc

which results in an interface annotated like:
```java
public interface Directory$ extends Directory {
            @Override
            @Query("where id in ?1 order by '' limit 1")
            @OrderBy(value="age", descending = true)
            public java.util.List<java.lang.String> findFirstNameByIdInOrderByAgeDesc (java.util.List<java.lang.Long> ids);
}
```

but the return type should be type of `Person` rather than `firstName` values.

### Additional Context

_No response_

### Is there an existing challenge for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by KyleAure**
- fixes #640 
- Verifies that another Jakarta Data Provider does not attempt to implement the Dictonary repository
- Fixes the Signature Tests

~DRAFT - signatures need to be updated with jakarta.data.spi package, but a compile time failure was merged.~

### CODE REVIEW

File: tck/src/main/java/ee/jakarta/tck/data/common/cdi/Directory.java [hunk 1]
```diff
@@ -31,5 +35,12 @@ public interface Directory extends DataRepository<Person, Long> {
     //Self referencing provider so that this repository can be used for both WEB and CORE tests
     public static final String PERSON_PROVIDER = "PERSON_PROVIDER";
     
-    List<String> findFirstNameByIdInOrderByAgeDesc(List<Long> ids);
+    List<String> findLastNameByIdInOrderByAgeDesc(List<Long> ids);
```
Comment (gavinking) [inline tck/src/main/java/ee/jakarta/tck/data/common/cdi/Directory.java:38]: I think this is still wrong, isn't it? The problem wasn't that `First` was ambiguous, the problem was that QbMN simply does not have a projection operator.

Comment (KyleAure) [reply tck/src/main/java/ee/jakarta/tck/data/common/cdi/Directory.java]: Sorry had to re-read the spec to understand completely.  Updated the test so it should follow the query by method name BNF

**Comment by gavinking** [comment]
Nice, that looks better, thanks.

**Review by njr-11 — APPROVED** [review]
