### PR TITLE
Add test case for custom entity types and fix query methods for validation

### LINKED ISSUE #657: [TCK Challenge]: ee.jakarta.tck.data.web.validation.Rectangles has two bad methods
### Specification

@Delete, spec/src/main/asciidoc/method-query.asciidoc

### Assertion

Automatic query methods, QBN findBy...

### TCK Version

SNAPSHOT (Locally built)

### Implementation being tested

HIbernate

### Challenge Scenario

Something else

### Full Description

The `ee.jakarta.tck.data.web.validation.Rectangles` repository interface has what looks to be two invalid methods:

```java
@Repository
public interface Rectangles extends DataRepository<Rectangle, String> {
...
    void deleteAllBy();

    @Size(min = 0, max = 3)
    List<Rectangle> findAllByOrderByIdAsc();
}
```

### Additional Context

The `deleteAllBy` method is not a QBN method, and its usage in the TCK implies it should be annotated with `@Delete` to function as an automatic query method that deletes all entities in the repo.

The `findAllByOrderByIdAsc` method fails to parse as a QBN method because there is no predicate between the By and OrderBy, and the current documented QBN grammar does not allow for an empty predicate. It does not seem like there is an approriate QBN method for the given TCK usage to attempt to return all entities and order them by id. It seems like the correct method would be:
```java
    @Size(min = 0, max = 3)
    @Find
    @OrderBy(value = "id")
    List<Rectangle> findAllByOrderByIdAsc();
```

### Is there an existing challenge for this?

- [X] I have searched the existing issues

### LINKED ISSUE #660: Missing test case for custom entity types
It looks to me like they are cheating and relying on `@Repository(provider =` to be assigned the `Directory` repository,
```
@Repository(provider = Directory.PERSON_PROVIDER)
public interface Directory extends DataRepository<Person, Long> {
```

That means the coverage here isn't as good as it should be.  We should leave this in place because it's also a valid scenario and create a second repository for `Person` that omits `provider = ...` and instead relies on the type of Entity annotation.

_Originally posted by @njr-11 in https://github.com/jakartaee/data/issues/647#issuecomment-2038298851_

### PR DESCRIPTION
**Pull request by KyleAure**
- Fixes #657 
- Fixes #660

### CODE REVIEW

File: tck/src/main/java/ee/jakarta/tck/data/common/cdi/Person.java [hunk 1]
```diff
@@ -17,11 +17,7 @@
 
 /**
  * A test entity that will be persisted to a repository.
- * Uses the custom {@code @PersonEntity} annotation.
- * 
- * @see ee.jakarta.tck.data.common.cdi.PersonEntity
  */
-@PersonEntity
 public class Person {
```
Comment (njr-11) [inline tck/src/main/java/ee/jakarta/tck/data/common/cdi/Person.java:21]: Should we put the NoSQL and/or Persitence `@Entity` onto this to help test that Jakarta Data providers against which the TCK is run do not try to handle it because its repository specifically asks for the TCK mock Data provider `provider = Directory.PERSON_PROVIDER`?

**Comment by KyleAure** [comment]
Resolved merge conflicts.

**Review by mswatosh — APPROVED** [review]

**Review by njr-11 — APPROVED** [review]
